import { useMemo, useState } from "react";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { CalendarDays, ClipboardCheck, FileText, ArrowLeft } from "lucide-react";
import { canSubmitWorkLog, mondayForDate } from "@/lib/workLogValidation";

const localDate = () => new Date().toISOString().slice(0, 10);
const statusTone = (status: string) => status === "approved" || status === "reviewed" ? "badge-success" : "badge-warning";

function ClinicalSelectors({ clientId, doctorId, onClientChange, onDoctorChange, clients, doctors }: { clientId: string; doctorId: string; onClientChange: (value: string) => void; onDoctorChange: (value: string) => void; clients: Array<{ id: number; name: string }>; doctors: Array<{ id: number; clientId: number; name: string; specialty?: string | null }> }) {
  const matchingDoctors = doctors.filter((doctor) => doctor.clientId === Number(clientId));
  return <><label>Hospital / client</label><select className="blueprint-input" value={clientId} onChange={(event) => onClientChange(event.target.value)}><option value="">Select hospital from FFM database</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select><label>Doctor</label><select className="blueprint-input" value={doctorId} disabled={!clientId} onChange={(event) => onDoctorChange(event.target.value)}><option value="">{clientId ? "Select doctor at this hospital" : "Select hospital first"}</option>{matchingDoctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{doctor.name}{doctor.specialty ? ` — ${doctor.specialty}` : ""}</option>)}</select>{clientId && !matchingDoctors.length && <p className="muted">No doctor is registered under this hospital yet. Ask your Manager to add the doctor to the FFM database.</p>}</>;
}

export default function DelegateWorkLog() {
  const { user, loading, isAuthenticated } = useAuth();
  const utils = trpc.useUtils();
  const clientsQuery = trpc.operations.clients.useQuery(undefined, { enabled: isAuthenticated });
  const doctorsQuery = trpc.operations.doctors.useQuery(undefined, { enabled: isAuthenticated });
  const weeklyPlans = trpc.delegatePlanning.weeklyPlans.useQuery(undefined, { enabled: isAuthenticated });
  const dailyReports = trpc.delegatePlanning.dailyReports.useQuery(undefined, { enabled: isAuthenticated });
  const submitWeekly = trpc.delegatePlanning.submitWeeklyPlan.useMutation({ onSuccess: () => utils.delegatePlanning.weeklyPlans.invalidate() });
  const submitDaily = trpc.delegatePlanning.submitDailyReport.useMutation({ onSuccess: () => utils.delegatePlanning.dailyReports.invalidate() });
  const reviewWeekly = trpc.delegatePlanning.reviewWeeklyPlan.useMutation({ onSuccess: () => utils.delegatePlanning.weeklyPlans.invalidate() });
  const reviewDaily = trpc.delegatePlanning.reviewDailyReport.useMutation({ onSuccess: () => utils.delegatePlanning.dailyReports.invalidate() });
  const [weekOf, setWeekOf] = useState(() => mondayForDate(localDate()));
  const [weeklyClientId, setWeeklyClientId] = useState("");
  const [weeklyDoctorId, setWeeklyDoctorId] = useState("");
  const [dailyClientId, setDailyClientId] = useState("");
  const [dailyDoctorId, setDailyDoctorId] = useState("");
  const [objectives, setObjectives] = useState("");
  const [plannedVisits, setPlannedVisits] = useState("");
  const [supportNeeded, setSupportNeeded] = useState("");
  const [reportDate, setReportDate] = useState(localDate());
  const [summary, setSummary] = useState("");
  const [outcomes, setOutcomes] = useState("");
  const [challenges, setChallenges] = useState("");
  const [nextActions, setNextActions] = useState("");
  const [notice, setNotice] = useState("");
  const isDelegate = user?.role === "delegate";
  const isManager = user?.role === "manager";
  const clients = clientsQuery.data ?? [];
  const doctors = doctorsQuery.data ?? [];
  const busy = clientsQuery.isLoading || doctorsQuery.isLoading;
  const clientName = (id: number) => clients.find((client) => client.id === id)?.name || "Hospital";
  const doctorName = (id: number) => doctors.find((doctor) => doctor.id === id)?.name || "Doctor";

  if (loading) return <div className="blueprint-page"><div className="blueprint-loader">Loading FFM Work Log…</div></div>;
  if (!isDelegate && !isManager) return <div className="blueprint-page"><Card className="login-card blueprint-card"><h1>Work Log is role restricted</h1><p className="muted">This workspace is for Delegates and their assigned Managers.</p></Card></div>;
  return <div className="blueprint-page"><div className="blueprint-grid"/><main className="container py-8 relative z-10"><a href={isDelegate ? "/delegate" : "/"} className="inline-flex items-center gap-2 text-sm text-cyan-300 mb-6"><ArrowLeft size={16}/> Back to workspace</a><div className="mb-8"><p className="eyebrow">FFM / FIELD PERFORMANCE</p><h1 className="text-4xl font-bold text-white">{isDelegate ? "My weekly plan & daily reports" : "Delegate plans & daily reports"}</h1><p className="muted mt-2">{isDelegate ? "Select the hospital and linked doctor from FFM, then submit your plan or report directly in the app." : "Review submissions from your assigned Delegates without waiting for exported files."}</p></div>{notice && <div className="admin-feedback success mb-5">{notice}</div>}
    {isDelegate && <div className="grid lg:grid-cols-2 gap-6"><Card className="blueprint-card"><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays size={20}/> Weekly visit plan</CardTitle><p className="muted">One hospital and one linked doctor per submitted plan.</p></CardHeader><CardContent className="form-stack"><ClinicalSelectors clientId={weeklyClientId} doctorId={weeklyDoctorId} onClientChange={(value) => { setWeeklyClientId(value); setWeeklyDoctorId(""); }} onDoctorChange={setWeeklyDoctorId} clients={clients} doctors={doctors}/><label>Week starting Monday</label><Input type="date" value={weekOf} onChange={(event) => setWeekOf(mondayForDate(event.target.value))}/><label>Weekly objectives</label><Textarea value={objectives} onChange={(event) => setObjectives(event.target.value)} placeholder="Priority objectives and expected outcomes…"/><label>Planned visits</label><Textarea value={plannedVisits} onChange={(event) => setPlannedVisits(event.target.value)} placeholder="Date — client contact — purpose — expected result…"/><label>Support needed (optional)</label><Textarea value={supportNeeded} onChange={(event) => setSupportNeeded(event.target.value)} placeholder="Decision, delivery, or Manager support needed…"/><Button className="blueprint-button" disabled={busy || submitWeekly.isPending || !weeklyClientId || !weeklyDoctorId || !canSubmitWorkLog(objectives, plannedVisits)} onClick={() => submitWeekly.mutate({ clientId: Number(weeklyClientId), doctorId: Number(weeklyDoctorId), weekOf: new Date(`${weekOf}T12:00:00`), objectives, plannedVisits, supportNeeded: supportNeeded || undefined }, { onSuccess: () => { setObjectives(""); setPlannedVisits(""); setSupportNeeded(""); setNotice("Weekly visit plan submitted for Manager review."); }, onError: (error) => setNotice(error.message) })}>{submitWeekly.isPending ? "Submitting…" : "Submit weekly plan"}</Button></CardContent></Card>
      <Card className="blueprint-card"><CardHeader><CardTitle className="flex items-center gap-2"><FileText size={20}/> Daily activity report</CardTitle><p className="muted">Record the daily outcome for a selected hospital and doctor.</p></CardHeader><CardContent className="form-stack"><ClinicalSelectors clientId={dailyClientId} doctorId={dailyDoctorId} onClientChange={(value) => { setDailyClientId(value); setDailyDoctorId(""); }} onDoctorChange={setDailyDoctorId} clients={clients} doctors={doctors}/><label>Report date</label><Input type="date" value={reportDate} onChange={(event) => setReportDate(event.target.value)}/><label>Activity summary</label><Textarea value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="Visit, discussion, and key activity…"/><label>Outcomes achieved</label><Textarea value={outcomes} onChange={(event) => setOutcomes(event.target.value)} placeholder="Confirmed decisions, completed actions, and results…"/><label>Challenges (optional)</label><Textarea value={challenges} onChange={(event) => setChallenges(event.target.value)} placeholder="Delays, missing data, or help needed…"/><label>Next actions (optional)</label><Textarea value={nextActions} onChange={(event) => setNextActions(event.target.value)} placeholder="Action — owner — expected date…"/><Button className="blueprint-button" disabled={busy || submitDaily.isPending || !dailyClientId || !dailyDoctorId || !canSubmitWorkLog(summary, outcomes)} onClick={() => submitDaily.mutate({ clientId: Number(dailyClientId), doctorId: Number(dailyDoctorId), reportDate: new Date(`${reportDate}T12:00:00`), summary, outcomes, challenges: challenges || undefined, nextActions: nextActions || undefined }, { onSuccess: () => { setSummary(""); setOutcomes(""); setChallenges(""); setNextActions(""); setNotice("Daily activity report submitted for Manager review."); }, onError: (error) => setNotice(error.message) })}>{submitDaily.isPending ? "Submitting…" : "Submit daily report"}</Button></CardContent></Card></div>}
    <div className="grid lg:grid-cols-2 gap-6 mt-6"><Card className="blueprint-card"><CardHeader><CardTitle>Weekly plans</CardTitle></CardHeader><CardContent className="space-y-4">{weeklyPlans.isLoading ? <p className="muted">Loading weekly plans…</p> : weeklyPlans.data?.length ? weeklyPlans.data.map((plan) => <div key={plan.id} className="border border-slate-700 p-4"><div className="flex justify-between gap-3"><strong>{isManager ? plan.delegateName : `Week of ${new Date(plan.weekOf).toLocaleDateString()}`}</strong><Badge className={statusTone(plan.status)}>{plan.status}</Badge></div>{isManager && <p className="muted text-sm">Week of {new Date(plan.weekOf).toLocaleDateString()}</p>}<p className="mt-2 text-cyan-200"><strong>{clientName(plan.clientId)}</strong> · {doctorName(plan.doctorId)}</p><p className="mt-2 text-white"><strong>Objectives:</strong> {plan.objectives}</p><p className="mt-2 muted whitespace-pre-wrap"><strong>Visits:</strong> {plan.plannedVisits}</p>{plan.supportNeeded && <p className="mt-2 muted"><strong>Support:</strong> {plan.supportNeeded}</p>}{plan.reviewNote && <p className="mt-2 text-cyan-200"><strong>Manager note:</strong> {plan.reviewNote}</p>}{isManager && plan.status === "pending" && <div className="flex gap-2 mt-3"><Button size="sm" className="blueprint-button" onClick={() => reviewWeekly.mutate({ id: plan.id, status: "approved" })}>Approve</Button><Button size="sm" variant="outline" onClick={() => reviewWeekly.mutate({ id: plan.id, status: "rejected", reviewNote: "Please revise the plan and resubmit." })}>Request revision</Button></div>}</div>) : <p className="muted">No weekly plans submitted yet.</p>}</CardContent></Card>
      <Card className="blueprint-card"><CardHeader><CardTitle>Daily reports</CardTitle></CardHeader><CardContent className="space-y-4">{dailyReports.isLoading ? <p className="muted">Loading daily reports…</p> : dailyReports.data?.length ? dailyReports.data.map((report) => <div key={report.id} className="border border-slate-700 p-4"><div className="flex justify-between gap-3"><strong>{isManager ? report.delegateName : new Date(report.reportDate).toLocaleDateString()}</strong><Badge className={statusTone(report.status)}>{report.status}</Badge></div>{isManager && <p className="muted text-sm">{new Date(report.reportDate).toLocaleDateString()}</p>}<p className="mt-2 text-cyan-200"><strong>{clientName(report.clientId)}</strong> · {doctorName(report.doctorId)}</p><p className="mt-2 text-white"><strong>Summary:</strong> {report.summary}</p><p className="mt-2 muted"><strong>Outcomes:</strong> {report.outcomes}</p>{report.challenges && <p className="mt-2 muted"><strong>Challenges:</strong> {report.challenges}</p>}{report.nextActions && <p className="mt-2 muted"><strong>Next:</strong> {report.nextActions}</p>}{report.managerNote && <p className="mt-2 text-cyan-200"><strong>Manager note:</strong> {report.managerNote}</p>}{isManager && report.status === "submitted" && <Button size="sm" className="blueprint-button mt-3" onClick={() => reviewDaily.mutate({ id: report.id })}><ClipboardCheck size={15}/> Mark reviewed</Button>}</div>) : <p className="muted">No daily reports submitted yet.</p>}</CardContent></Card></div>
  </main></div>;
}
