import { createCipheriv, createDecipheriv, createHash, randomBytes } from "crypto";
import { and, eq } from "drizzle-orm";
import { auditEvents, backupArchives, clients, doctors, evidence, geography, googleDriveBackupConnections, implantCatalogue, invitations, managerDelegateAssignments, managerWarehouseHeroAssignments, messages, surgeries, surgeryDeliveryProofs, surgeryImplants, tasks, userNotifications, users, visitPlans, visits, warehouseDeliveryProofs, warehouseHeroLocations } from "../drizzle/schema";
import { addAuditEvent, completeBackupArchive, createBackupArchive, exportFfmOperationalSnapshot, failBackupArchive, getGoogleDriveBackupConnection, upsertGoogleDriveBackupConnection } from "./db";
import { getDb } from "./db";

export const GOOGLE_DRIVE_BACKUP_FOLDER_ID = "1-bkRfhqNqzwzG9lw08Ub8bDf-RGvVE55";
export const GOOGLE_DRIVE_CALLBACK_URL = "https://ffmmanager-9wxfbeae.manus.space/api/oauth/google-drive/callback";
const GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token";
const restoreKeys = ["users", "invitations", "clients", "doctors", "managerDelegateAssignments", "managerWarehouseHeroAssignments", "warehouseHeroLocations", "warehouseDeliveryProofs", "tasks", "visits", "evidence", "auditEvents", "messages", "userNotifications", "surgeries", "implantCatalogue", "surgeryImplants", "surgeryDeliveryProofs", "visitPlans", "geography"] as const;
type RestoreSnapshot = { format: "ffm-operational-snapshot-v1"; generatedAt: string; scope: { originalBinaryFilesIncluded: boolean }; data: Record<(typeof restoreKeys)[number], unknown[]> };
export function restoreConfirmationPhrase(archiveId: number) { return `RESTORE ${archiveId}`; }
function validateRestoreSnapshot(value: unknown): RestoreSnapshot { if (!value || typeof value !== "object") throw new Error("Backup archive is not valid JSON"); const snapshot = value as Partial<RestoreSnapshot>; if (snapshot.format !== "ffm-operational-snapshot-v1" || !snapshot.data || typeof snapshot.data !== "object") throw new Error("This file is not an FFM operational snapshot"); for (const key of restoreKeys) if (!Array.isArray(snapshot.data[key])) throw new Error(`Backup archive is missing ${key}`); return snapshot as RestoreSnapshot; }
function restoreCounts(snapshot: RestoreSnapshot) { return Object.fromEntries(restoreKeys.map((key) => [key, snapshot.data[key].length])); }
async function loadRestoreArchive(userId: number, archiveId: number) { const db = await getDb(); if (!db) throw new Error("Database is not available"); const connection = (await db.select().from(googleDriveBackupConnections).where(eq(googleDriveBackupConnections.userId, userId)).limit(1))[0]; const archive = (await db.select().from(backupArchives).where(and(eq(backupArchives.id, archiveId), eq(backupArchives.createdBy, userId))).limit(1))[0]; if (!connection || !archive?.googleDriveFileId || archive.status !== "completed") throw new Error("Select a completed FFM backup archive"); const response = await fetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(archive.googleDriveFileId)}?alt=media`, { headers: { Authorization: `Bearer ${await refreshGoogleAccessToken(decryptGoogleRefreshToken(connection.encryptedRefreshToken))}` } }); if (!response.ok) throw new Error("Unable to download the selected Google Drive archive"); const bytes = Buffer.from(await response.arrayBuffer()); if (bytes.length > 50 * 1024 * 1024) throw new Error("Backup archive is too large for safe in-app restoration"); return { archive, snapshot: validateRestoreSnapshot(JSON.parse(bytes.toString("utf8"))) }; }
export async function previewGoogleDriveBackupRestore(userId: number, archiveId: number) { const { archive, snapshot } = await loadRestoreArchive(userId, archiveId); return { archiveId, fileName: archive.fileName, generatedAt: snapshot.generatedAt, recordCounts: restoreCounts(snapshot), originalBinaryFilesIncluded: snapshot.scope.originalBinaryFilesIncluded, confirmationPhrase: restoreConfirmationPhrase(archiveId) }; }
export async function restoreGoogleDriveBackupArchive(userId: number, archiveId: number, confirmation: string) { if (confirmation.trim() !== restoreConfirmationPhrase(archiveId)) throw new Error("Type the exact restore confirmation phrase"); const { archive, snapshot } = await loadRestoreArchive(userId, archiveId); const rollbackArchive = await createGoogleDriveBackupArchive(userId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const data = snapshot.data; const rows = (key: keyof RestoreSnapshot["data"]) => data[key] as any[]; await db.transaction(async (tx) => { for (const table of [userNotifications, surgeryDeliveryProofs, surgeryImplants, surgeries, evidence, visits, tasks, visitPlans, messages, warehouseDeliveryProofs, warehouseHeroLocations, managerDelegateAssignments, managerWarehouseHeroAssignments, doctors, geography, clients, invitations, implantCatalogue, auditEvents, users]) await tx.delete(table); const inserts: Array<[any, any[]]> = [[users, rows("users")], [invitations, rows("invitations")], [clients, rows("clients")], [doctors, rows("doctors")], [geography, rows("geography")], [managerDelegateAssignments, rows("managerDelegateAssignments")], [managerWarehouseHeroAssignments, rows("managerWarehouseHeroAssignments")], [warehouseHeroLocations, rows("warehouseHeroLocations")], [warehouseDeliveryProofs, rows("warehouseDeliveryProofs")], [tasks, rows("tasks")], [visits, rows("visits")], [evidence, rows("evidence")], [messages, rows("messages")], [userNotifications, rows("userNotifications")], [surgeries, rows("surgeries")], [implantCatalogue, rows("implantCatalogue")], [surgeryImplants, rows("surgeryImplants")], [surgeryDeliveryProofs, rows("surgeryDeliveryProofs")], [visitPlans, rows("visitPlans")], [auditEvents, rows("auditEvents")]]; for (const [table, values] of inserts) if (values.length) await tx.insert(table).values(values); }); await db.insert(auditEvents).values({ actorId: userId, action: "backup.google_drive_restored", entityType: "backupArchive", entityId: archiveId, metadata: JSON.stringify({ sourceFileName: archive.fileName, rollbackArchiveId: rollbackArchive.id, restoredCounts: restoreCounts(snapshot) }) }); return { sourceFileName: archive.fileName, rollbackArchive, restoredCounts: restoreCounts(snapshot) }; }
function credential(name: "GOOGLE_DRIVE_CLIENT_ID" | "GOOGLE_DRIVE_CLIENT_SECRET") { const value = process.env[name]; if (!value) throw new Error(`${name} is not configured`); return value; }
function encryptionKey() { const secret = process.env.JWT_SECRET; if (!secret) throw new Error("JWT_SECRET is not configured"); return createHash("sha256").update(secret).digest(); }
export function encryptGoogleRefreshToken(value: string) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return `${iv.toString("base64url")}.${cipher.getAuthTag().toString("base64url")}.${encrypted.toString("base64url")}`; }
export function decryptGoogleRefreshToken(value: string) { const [ivValue, tagValue, ciphertext] = value.split("."); if (!ivValue || !tagValue || !ciphertext) throw new Error("Stored Google Drive connection is invalid"); const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(ivValue, "base64url")); decipher.setAuthTag(Buffer.from(tagValue, "base64url")); return Buffer.concat([decipher.update(Buffer.from(ciphertext, "base64url")), decipher.final()]).toString("utf8"); }
export function buildGoogleDriveAuthorizationUrl(state: string) { const params = new URLSearchParams({ client_id: credential("GOOGLE_DRIVE_CLIENT_ID"), redirect_uri: GOOGLE_DRIVE_CALLBACK_URL, response_type: "code", scope: "openid email https://www.googleapis.com/auth/drive.file", access_type: "offline", prompt: "consent", state }); return `https://accounts.google.com/o/oauth2/v2/auth?${params}`; }
export async function exchangeGoogleAuthorizationCode(code: string) { const body = new URLSearchParams({ code, client_id: credential("GOOGLE_DRIVE_CLIENT_ID"), client_secret: credential("GOOGLE_DRIVE_CLIENT_SECRET"), redirect_uri: GOOGLE_DRIVE_CALLBACK_URL, grant_type: "authorization_code" }); const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", body }); const payload = await response.json() as { access_token?: string; refresh_token?: string; error?: string }; if (!response.ok || !payload.refresh_token) throw new Error(payload.error === "invalid_grant" ? "Google authorization expired; connect Google Drive again" : "Google did not return a reusable Drive connection"); return payload; }
async function getGoogleEmail(accessToken: string) { const response = await fetch("https://openidconnect.googleapis.com/v1/userinfo", { headers: { Authorization: `Bearer ${accessToken}` } }); const payload = await response.json() as { email?: string }; return response.ok ? payload.email ?? null : null; }
export async function saveGoogleDriveBackupConnection(userId: number, code: string) { const token = await exchangeGoogleAuthorizationCode(code); const googleEmail = token.access_token ? await getGoogleEmail(token.access_token) : null; return upsertGoogleDriveBackupConnection({ userId, googleEmail, folderId: GOOGLE_DRIVE_BACKUP_FOLDER_ID, encryptedRefreshToken: encryptGoogleRefreshToken(token.refresh_token!) }); }
async function refreshGoogleAccessToken(refreshToken: string) { const body = new URLSearchParams({ refresh_token: refreshToken, client_id: credential("GOOGLE_DRIVE_CLIENT_ID"), client_secret: credential("GOOGLE_DRIVE_CLIENT_SECRET"), grant_type: "refresh_token" }); const response = await fetch(GOOGLE_TOKEN_URL, { method: "POST", body }); const payload = await response.json() as { access_token?: string; error?: string }; if (!response.ok || !payload.access_token) throw new Error(payload.error === "invalid_grant" ? "Google Drive connection expired; reconnect Google Drive" : "Unable to refresh Google Drive authorization"); return payload.access_token; }
async function uploadSnapshot(accessToken: string, folderId: string, fileName: string, bytes: Buffer) { const boundary = `ffm_backup_${randomBytes(12).toString("hex")}`; const metadata = JSON.stringify({ name: fileName, parents: [folderId], mimeType: "application/json", description: "FFM operational database snapshot and evidence manifest" }); const body = Buffer.concat([Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n`), bytes, Buffer.from(`\r\n--${boundary}--\r\n`)]); const response = await fetch("https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name", { method: "POST", headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": `multipart/related; boundary=${boundary}` }, body }); const payload = await response.json() as { id?: string; error?: { message?: string } }; if (!response.ok || !payload.id) throw new Error(payload.error?.message || "Google Drive upload failed"); return payload.id; }
export async function createGoogleDriveBackupArchive(userId: number) { const connection = await getGoogleDriveBackupConnection(userId); if (!connection) throw new Error("Connect Google Drive before starting an FFM backup"); const timestamp = new Date().toISOString().replace(/[:.]/g, "-"); const fileName = `ffm-operational-backup-${timestamp}.json`; const archive = await createBackupArchive({ createdBy: userId, fileName, status: "running" }); try { const snapshot = await exportFfmOperationalSnapshot(); const bytes = Buffer.from(JSON.stringify(snapshot, null, 2)); const accessToken = await refreshGoogleAccessToken(decryptGoogleRefreshToken(connection.encryptedRefreshToken)); const driveFileId = await uploadSnapshot(accessToken, connection.folderId, fileName, bytes); await completeBackupArchive(archive.id, { googleDriveFileId: driveFileId, sizeBytes: bytes.length }); await addAuditEvent({ actorId: userId, action: "backup.google_drive_created", entityType: "backupArchive", entityId: archive.id, metadata: JSON.stringify({ fileName, sizeBytes: bytes.length, driveFileId }) }); return { id: archive.id, fileName, sizeBytes: bytes.length, driveFileId }; } catch (error) { await failBackupArchive(archive.id, error instanceof Error ? error.message : "Backup failed"); throw error; } }
