import { createHash, randomBytes } from "node:crypto";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME, FFM_MAGIC_SESSION_COOKIE } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { acceptInvitation, activateInvitedUser, addAuditEvent, addEvidence, createClient, updateClient, removeClient, createDoctor, getDoctorById, updateDoctor, removeDoctor, createGeography, getGeographyById, updateGeography, removeGeography, createInvitation, canUserUpdateTask, canManagerAccessDelegate, normalizeVisitReport, createTask, getClientById, getInvitationByHash, getOperationalSummary, getTaskById, getUserById, getVisitByTaskId, getVisitPlanById, getSurgeryById, listAllTasks, listAuditEvents, listClients, listDelegates, listDelegatesForManager, listWarehouseHeroes, listWarehouseHeroesForManager, listWarehouseHeroLocationsForManager, listWarehouseDeliveryProofsForManager, createWarehouseDeliveryProof, listDoctors, listGeography, listInvitations, listMessages, listSurgeriesForDelegate, listSurgeriesForManager, listTasksForDelegate, listTasksForManager, listDelegateIdsForManager, listWarehouseHeroIdsForManager, listUsers, listManagers, listManagerAssignments, listManagerWarehouseHeroAssignments, listVisitPlansForDelegate, listVisitPlansForManager, listAllVisitPlans, listLiveDelegatePositionsForManager, createMessage, createSurgery, createVisitPlan, updateSurgery, updateVisitPlan, updateNotificationPreferences, removeUser, removeManagerDelegateAssignment, createManagerDelegateAssignment, createManagerWarehouseHeroAssignment, removeManagerWarehouseHeroAssignment, isDelegateAssignedToManager, isWarehouseHeroAssignedToManager, hasManagerForWarehouseHero, getWarehouseHeroLocation, upsertWarehouseHeroLocation, updateTaskStatus, updateUserRole, upsertUser, upsertVisit, isProtectedAdminTarget, operationalSummaryCsv, prepareVisitReport, captureClientError, listClientErrors, getMonitoringHealth } from "./db";
import { storagePut } from "./storage";
import { sdk } from "./_core/sdk";

const ADMIN_EMAIL = "dr.seleam@gmail.com";
const isAdmin = (user: { email?: string | null; role?: string }) => user.email?.toLowerCase() === ADMIN_EMAIL || user.role === "admin";
const canManage = (user: { email?: string | null; role?: string }) => isAdmin(user) || user.role === "manager";
const adminOnly = protectedProcedure.use(({ ctx, next }) => { if (!isAdmin(ctx.user)) throw new TRPCError({ code: "FORBIDDEN", message: "Administrator access required" }); return next({ ctx }); });
const managerOnly = protectedProcedure.use(({ ctx, next }) => { if (!canManage(ctx.user)) throw new TRPCError({ code: "FORBIDDEN", message: "Manager access required" }); return next({ ctx }); });
const warehouseHeroOnly = protectedProcedure.use(({ ctx, next }) => { if (ctx.user.role !== "warehouse_hero") throw new TRPCError({ code: "FORBIDDEN", message: "Warehouse Hero access required" }); return next({ ctx }); });
const tokenHash = (token: string) => createHash("sha256").update(token).digest("hex");

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(({ ctx }) => { if (ctx.authTimedOut) throw new TRPCError({ code: "UNAUTHORIZED", message: "Session verification timed out. Please sign in again." }); return ctx.user; }),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); ctx.res.clearCookie(FFM_MAGIC_SESSION_COOKIE, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  invitations: router({
    preview: publicProcedure.input(z.object({ token: z.string().min(20) })).query(async ({ input }) => { const invitation = await getInvitationByHash(tokenHash(input.token)); if (!invitation || invitation.acceptedAt || invitation.expiresAt < new Date()) throw new TRPCError({ code: "NOT_FOUND", message: "Invitation is invalid or expired" }); return { email: invitation.email, role: invitation.role, expiresAt: invitation.expiresAt }; }),
    accept: protectedProcedure.input(z.object({ token: z.string().min(20) })).mutation(async ({ input, ctx }) => { const invitation = await getInvitationByHash(tokenHash(input.token)); if (!invitation || invitation.acceptedAt || invitation.expiresAt < new Date()) throw new TRPCError({ code: "BAD_REQUEST", message: "Invitation is invalid or expired" }); if (ctx.user.email?.toLowerCase() !== invitation.email.toLowerCase()) throw new TRPCError({ code: "FORBIDDEN", message: "This invitation belongs to a different email address" }); await upsertUser({ openId: ctx.user.openId, email: ctx.user.email, name: ctx.user.name, role: invitation.role, loginMethod: ctx.user.loginMethod }); await acceptInvitation(invitation.id); await addAuditEvent({ actorId: ctx.user.id, action: "invitation.accepted", entityType: "invitation", entityId: invitation.id }); return { success: true, role: invitation.role } as const; }),
    acceptMagic: publicProcedure.input(z.object({ token: z.string().min(20) })).mutation(async ({ input, ctx }) => { const invitation = await getInvitationByHash(tokenHash(input.token)); if (!invitation || invitation.acceptedAt || invitation.expiresAt < new Date()) throw new TRPCError({ code: "BAD_REQUEST", message: "Invitation is invalid or expired" }); const invitedUser = await activateInvitedUser({ email: invitation.email, role: invitation.role }); if (!invitedUser) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Unable to activate invitation" }); await acceptInvitation(invitation.id); await addAuditEvent({ actorId: invitedUser.id, action: "invitation.accepted_magic_link", entityType: "invitation", entityId: invitation.id }); const sessionToken = await sdk.createSessionToken(invitedUser.openId, { expiresInMs: 1000 * 60 * 60 * 12, name: invitedUser.name || invitedUser.email || invitation.email }); ctx.res.cookie(FFM_MAGIC_SESSION_COOKIE, sessionToken, { ...getSessionCookieOptions(ctx.req), maxAge: 1000 * 60 * 60 * 12 }); return { success: true, role: invitation.role } as const; }),
  }),
  admin: router({
    users: adminOnly.query(async () => listUsers()),
    invitations: adminOnly.query(async () => listInvitations()),
    managers: adminOnly.query(async () => listManagers()),
    delegates: adminOnly.query(async () => listDelegates()),
    warehouseHeroes: adminOnly.query(async () => listWarehouseHeroes()),
    managerAssignments: adminOnly.query(async () => listManagerAssignments()),
    managerWarehouseHeroAssignments: adminOnly.query(async () => listManagerWarehouseHeroAssignments()),
    assignDelegate: adminOnly.input(z.object({ managerId: z.number().int().positive(), delegateId: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const manager = await getUserById(input.managerId); const delegate = await getUserById(input.delegateId); if (manager?.role !== "manager" || delegate?.role !== "delegate") throw new TRPCError({ code: "BAD_REQUEST", message: "Choose a valid manager and delegate" }); if (await isDelegateAssignedToManager(input.managerId, input.delegateId)) throw new TRPCError({ code: "CONFLICT", message: "This delegate is already assigned to that manager" }); const result = await createManagerDelegateAssignment({ ...input, assignedBy: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "manager_delegate.assigned", entityType: "managerDelegateAssignment", entityId: result?.id, metadata: JSON.stringify(input) }); return result; }),
    unassignDelegate: adminOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const result = await removeManagerDelegateAssignment(input.id); await addAuditEvent({ actorId: ctx.user.id, action: "manager_delegate.unassigned", entityType: "managerDelegateAssignment", entityId: input.id }); return result; }),
    assignWarehouseHero: adminOnly.input(z.object({ managerId: z.number().int().positive(), warehouseHeroId: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const manager = await getUserById(input.managerId); const warehouseHero = await getUserById(input.warehouseHeroId); if (manager?.role !== "manager" || warehouseHero?.role !== "warehouse_hero") throw new TRPCError({ code: "BAD_REQUEST", message: "Choose a valid manager and Warehouse Hero" }); if (await isWarehouseHeroAssignedToManager(input.managerId, input.warehouseHeroId)) throw new TRPCError({ code: "CONFLICT", message: "This Warehouse Hero is already assigned to that manager" }); const result = await createManagerWarehouseHeroAssignment({ ...input, assignedBy: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "manager_warehouse_hero.assigned", entityType: "managerWarehouseHeroAssignment", entityId: result?.id, metadata: JSON.stringify(input) }); return result; }),
    unassignWarehouseHero: adminOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const result = await removeManagerWarehouseHeroAssignment(input.id); await addAuditEvent({ actorId: ctx.user.id, action: "manager_warehouse_hero.unassigned", entityType: "managerWarehouseHeroAssignment", entityId: input.id }); return result; }),
    createInvitation: adminOnly.input(z.object({ email: z.string().email(), role: z.enum(["user", "manager", "delegate", "warehouse_hero"]).default("delegate") })).mutation(async ({ input, ctx }) => { const token = randomBytes(32).toString("hex"); const invitation = await createInvitation({ email: input.email.toLowerCase(), role: input.role, invitedBy: ctx.user.id, tokenHash: tokenHash(token), expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 72) }); await addAuditEvent({ actorId: ctx.user.id, action: "invitation.created", entityType: "invitation", entityId: invitation?.id }); return { invitation, token, inviteUrl: `/invite/${token}` }; }),
    addUser: adminOnly.input(z.object({ email: z.string().email(), name: z.string().trim().min(1).max(120).optional() })).mutation(async ({ input, ctx }) => { const existing = await listUsers(); if (existing.some((item) => item.email?.toLowerCase() === input.email.toLowerCase())) throw new TRPCError({ code: "CONFLICT", message: "A user with this email already exists" }); return createInvitation({ email: input.email.toLowerCase(), role: "delegate", invitedBy: ctx.user.id, tokenHash: tokenHash(randomBytes(32).toString("hex")), expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 72) }); }),
    setRole: adminOnly.input(z.object({ id: z.number().int().positive(), role: z.enum(["user", "manager", "delegate", "warehouse_hero", "admin"]) })).mutation(async ({ input, ctx }) => { const target = await getUserById(input.id); if (!target) throw new TRPCError({ code: "NOT_FOUND", message: "User not found" }); if (isProtectedAdminTarget(target, ctx.user.openId)) throw new TRPCError({ code: "FORBIDDEN", message: "The protected administrator role cannot be changed" }); const result = await updateUserRole(input.id, input.role); await addAuditEvent({ actorId: ctx.user.id, action: "user.role_changed", entityType: "user", entityId: input.id, metadata: JSON.stringify({ role: input.role }) }); return result; }),
    removeUser: adminOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const target = await getUserById(input.id); if (!target) throw new TRPCError({ code: "NOT_FOUND", message: "User not found" }); if (isProtectedAdminTarget(target, ctx.user.openId)) throw new TRPCError({ code: "FORBIDDEN", message: "The protected administrator account cannot be removed" }); await removeUser(input.id); await addAuditEvent({ actorId: ctx.user.id, action: "user.removed", entityType: "user", entityId: input.id }); return { success: true } as const; }),
  }),
  reports: router({
    summary: managerOnly.input(z.object({ from: z.string().optional(), to: z.string().optional() }).optional()).query(async ({ input, ctx }) => getOperationalSummary({ ...input, delegateIds: ctx.user.role === "manager" ? await listDelegateIdsForManager(ctx.user.id) : undefined })),
    exportCsv: managerOnly.input(z.object({ from: z.string().optional(), to: z.string().optional() }).optional()).query(async ({ input, ctx }) => { const summary = await getOperationalSummary({ ...input, delegateIds: ctx.user.role === "manager" ? await listDelegateIdsForManager(ctx.user.id) : undefined }); return operationalSummaryCsv(summary); }),
    audit: adminOnly.input(z.object({ limit: z.number().int().min(1).max(200).default(100) }).optional()).query(({ input }) => listAuditEvents(input?.limit ?? 100)),
  }),
  monitoring: router({
    captureClientError: protectedProcedure.input(z.object({ message: z.string().min(1).max(500), stack: z.string().max(20000).optional(), componentStack: z.string().max(20000).optional(), route: z.string().max(255).optional() })).mutation(async ({ input, ctx }) => { await captureClientError({ ...input, userId: ctx.user.id }); return { success: true } as const; }),
    recentClientErrors: adminOnly.input(z.object({ limit: z.number().int().min(1).max(200).default(100) }).optional()).query(({ input }) => listClientErrors(input?.limit ?? 100)),
    health: adminOnly.query(() => getMonitoringHealth()),
  }),
  preferences: router({
    get: protectedProcedure.query(({ ctx }) => getUserById(ctx.user.id).then((user) => ({ pushNotifications: user?.pushNotifications ?? true, emailNotifications: user?.emailNotifications ?? true, locationSharing: user?.locationSharing ?? false }))),
    update: protectedProcedure.input(z.object({ pushNotifications: z.boolean().optional(), emailNotifications: z.boolean().optional(), locationSharing: z.boolean().optional() }).refine((input) => input.pushNotifications !== undefined || input.emailNotifications !== undefined || input.locationSharing !== undefined, { message: "At least one preference is required" })).mutation(async ({ input, ctx }) => { const result = await updateNotificationPreferences(ctx.user.id, input); await addAuditEvent({ actorId: ctx.user.id, action: "user.notification_preferences_updated", entityType: "user", entityId: ctx.user.id, metadata: JSON.stringify(input) }); return { pushNotifications: result?.pushNotifications ?? true, emailNotifications: result?.emailNotifications ?? true, locationSharing: result?.locationSharing ?? false }; }),
  }),
  operations: router({
    clients: protectedProcedure.query(() => listClients()),
    delegates: protectedProcedure.query(({ ctx }) => ctx.user.role === "manager" ? listDelegatesForManager(ctx.user.id) : listDelegates()),
    doctors: protectedProcedure.query(() => listDoctors()),
    geography: protectedProcedure.query(() => listGeography()),
    messages: protectedProcedure.query(({ ctx }) => listMessages(ctx.user.id)),
    surgeries: protectedProcedure.query(({ ctx }) => ctx.user.role === "delegate" ? listSurgeriesForDelegate(ctx.user.id) : ctx.user.role === "manager" ? listSurgeriesForManager(ctx.user.id) : listSurgeriesForDelegate(ctx.user.id)),
    visitPlans: protectedProcedure.query(({ ctx }) => ctx.user.role === "delegate" ? listVisitPlansForDelegate(ctx.user.id) : ctx.user.role === "manager" ? listVisitPlansForManager(ctx.user.id) : listAllVisitPlans()),
    liveDelegatePositions: managerOnly.query(({ ctx }) => listLiveDelegatePositionsForManager(ctx.user.id)),
    warehouseHeroes: managerOnly.query(({ ctx }) => ctx.user.role === "manager" ? listWarehouseHeroesForManager(ctx.user.id) : listWarehouseHeroes()),
    warehouseHeroLocations: managerOnly.query(({ ctx }) => listWarehouseHeroLocationsForManager(ctx.user.id, isAdmin(ctx.user))),
    warehouseDeliveryProofs: managerOnly.query(({ ctx }) => listWarehouseDeliveryProofsForManager(ctx.user.id, isAdmin(ctx.user))),
    updateWarehouseHeroLocation: warehouseHeroOnly.input(z.object({ latitude: z.string().regex(/^-?\d{1,3}(\.\d+)?$/).refine((value) => { const coordinate = Number(value); return coordinate >= -90 && coordinate <= 90; }, "Latitude must be between -90 and 90"), longitude: z.string().regex(/^-?\d{1,3}(\.\d+)?$/).refine((value) => { const coordinate = Number(value); return coordinate >= -180 && coordinate <= 180; }, "Longitude must be between -180 and 180") })).mutation(async ({ input, ctx }) => { const currentUser = await getUserById(ctx.user.id); if (!currentUser?.locationSharing) throw new TRPCError({ code: "FORBIDDEN", message: "Enable location sharing before updating Warehouse Hero GPS" }); if (!await hasManagerForWarehouseHero(ctx.user.id)) throw new TRPCError({ code: "FORBIDDEN", message: "An Administrator must assign you to a Manager before GPS tracking can start" }); const existing = await getWarehouseHeroLocation(ctx.user.id); if (existing && Date.now() - existing.capturedAt.getTime() < 10_000) return existing; const result = await upsertWarehouseHeroLocation({ warehouseHeroId: ctx.user.id, latitude: input.latitude, longitude: input.longitude, capturedAt: new Date() }); await addAuditEvent({ actorId: ctx.user.id, action: "warehouse_hero.location_updated", entityType: "warehouseHeroLocation", entityId: result?.id }); return result; }),
    uploadWarehouseDeliveryProof: warehouseHeroOnly.input(z.object({ fileName: z.string().min(1).max(180), mimeType: z.enum(["image/jpeg", "image/png", "image/webp"]), base64: z.string().min(20).max(15_000_000), note: z.string().max(1_000).optional() })).mutation(async ({ input, ctx }) => { if (!await hasManagerForWarehouseHero(ctx.user.id)) throw new TRPCError({ code: "FORBIDDEN", message: "An Administrator must assign you to a Manager before uploading delivery proof" }); const buffer = Buffer.from(input.base64.replace(/^data:[^;]+;base64,/, ""), "base64"); if (!buffer.byteLength) throw new TRPCError({ code: "BAD_REQUEST", message: "The delivery-proof image is empty" }); if (buffer.byteLength > 8 * 1024 * 1024) throw new TRPCError({ code: "PAYLOAD_TOO_LARGE", message: "Delivery-proof photos must be 8 MB or smaller" }); const safeName = input.fileName.replace(/[^a-zA-Z0-9._-]/g, "_"); const uploaded = await storagePut(`warehouse-delivery-proofs/${ctx.user.id}/${Date.now()}-${safeName}`, buffer, input.mimeType); const result = await createWarehouseDeliveryProof({ warehouseHeroId: ctx.user.id, note: input.note?.trim() || null, storageKey: uploaded.key, mimeType: input.mimeType, sizeBytes: buffer.byteLength, capturedAt: new Date() }); await addAuditEvent({ actorId: ctx.user.id, action: "warehouse_hero.delivery_proof_uploaded", entityType: "warehouseDeliveryProof", entityId: result?.id }); return { proofId: result?.id, url: uploaded.url } as const; }),
    submitVisitPlan: protectedProcedure.input(z.object({ clientId: z.number().int().positive(), proposedAt: z.date(), notes: z.string().max(5000).optional() })).mutation(async ({ input, ctx }) => { const result = await createVisitPlan({ ...input, delegateId: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "visit_plan.created", entityType: "visitPlan", entityId: result?.id }); return result; }),
    reviewVisitPlan: managerOnly.input(z.object({ id: z.number().int().positive(), status: z.enum(["approved", "rejected", "pending"]) })).mutation(async ({ input, ctx }) => { const existing = await getVisitPlanById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Visit plan not found" }); const allowedDelegateIds = await listDelegateIdsForManager(ctx.user.id); if (!canManagerAccessDelegate(ctx.user.role, ctx.user.id, existing.delegateId, allowedDelegateIds)) throw new TRPCError({ code: "FORBIDDEN", message: "This visit plan is outside the Manager assignment scope" }); const result = await updateVisitPlan(input.id, { status: input.status, reviewedBy: ctx.user.id, reviewedAt: new Date() }); await addAuditEvent({ actorId: ctx.user.id, action: "visit_plan.reviewed", entityType: "visitPlan", entityId: input.id, metadata: JSON.stringify({ status: input.status }) }); return result; }),
    addSurgery: protectedProcedure.input(z.object({ clientId: z.number().int().positive(), surgeryDate: z.date(), hospital: z.string().optional(), surgeon: z.string().optional(), procedureName: z.string().min(2), notes: z.string().optional() })).mutation(async ({ input, ctx }) => { const result = await createSurgery({ ...input, delegateId: ctx.user.id, createdBy: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "surgery.created", entityType: "surgery", entityId: result?.id }); return result; }),
    updateSurgery: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["pending", "partial", "collected"]).optional(), quotation: z.string().optional(), invoice: z.string().optional(), notes: z.string().optional() })).mutation(async ({ input, ctx }) => { const existing = await getSurgeryById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Surgery not found" }); if (ctx.user.role === "manager") { const allowedDelegateIds = await listDelegateIdsForManager(ctx.user.id); if (!canManagerAccessDelegate(ctx.user.role, ctx.user.id, existing.delegateId, allowedDelegateIds)) throw new TRPCError({ code: "FORBIDDEN", message: "This surgery is outside the Manager assignment scope" }); } else if (ctx.user.role === "delegate" && existing.delegateId !== ctx.user.id) throw new TRPCError({ code: "FORBIDDEN", message: "This surgery is outside your assignment scope" }); const result = await updateSurgery(input.id, input); await addAuditEvent({ actorId: ctx.user.id, action: "surgery.updated", entityType: "surgery", entityId: input.id }); return result; }),
    sendMessage: managerOnly.input(z.object({ recipientId: z.number().int().positive(), body: z.string().trim().min(1).max(5000) })).mutation(async ({ input, ctx }) => { const recipient = await getUserById(input.recipientId); if (!recipient || recipient.role !== "delegate") throw new TRPCError({ code: "BAD_REQUEST", message: "Choose an active Delegate recipient" }); if (ctx.user.role === "manager") { const allowedDelegateIds = await listDelegateIdsForManager(ctx.user.id); if (!allowedDelegateIds.includes(input.recipientId)) throw new TRPCError({ code: "FORBIDDEN", message: "This Delegate is outside the Manager assignment scope" }); } const result = await createMessage({ senderId: ctx.user.id, recipientId: input.recipientId, body: input.body }); await addAuditEvent({ actorId: ctx.user.id, action: "message.created", entityType: "message", entityId: result?.id, metadata: JSON.stringify({ recipientId: input.recipientId }) }); return result; }),
    addDoctor: managerOnly.input(z.object({ clientId: z.number().int().positive(), name: z.string().min(2), specialty: z.string().optional(), department: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional(), relationship: z.enum(["new", "warm", "kol", "cold"]).default("new"), notes: z.string().optional() })).mutation(async ({ input, ctx }) => { const result = await createDoctor({ ...input, createdBy: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "doctor.created", entityType: "doctor", entityId: result?.id }); return result; }),
    updateDoctor: managerOnly.input(z.object({ id: z.number().int().positive(), clientId: z.number().int().positive(), name: z.string().min(2), specialty: z.string().optional(), department: z.string().optional(), phone: z.string().optional(), email: z.string().email().optional(), relationship: z.enum(["new", "warm", "kol", "cold"]), notes: z.string().optional() })).mutation(async ({ input, ctx }) => { const existing = await getDoctorById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Doctor not found" }); const { id, ...changes } = input; const result = await updateDoctor(id, changes); await addAuditEvent({ actorId: ctx.user.id, action: "doctor.updated", entityType: "doctor", entityId: id }); return result; }),
    removeDoctor: managerOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const existing = await getDoctorById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Doctor not found" }); await removeDoctor(input.id); await addAuditEvent({ actorId: ctx.user.id, action: "doctor.removed", entityType: "doctor", entityId: input.id }); return { success: true } as const; }),
    addGeography: managerOnly.input(z.object({ kind: z.enum(["province", "city"]), name: z.string().min(2), parentId: z.number().int().positive().nullable().optional() })).mutation(async ({ input, ctx }) => { const result = await createGeography({ ...input, createdBy: ctx.user.id, parentId: input.parentId ?? null }); await addAuditEvent({ actorId: ctx.user.id, action: "geography.created", entityType: input.kind, entityId: result?.id }); return result; }),
    updateGeography: managerOnly.input(z.object({ id: z.number().int().positive(), kind: z.enum(["province", "city"]), name: z.string().min(2), parentId: z.number().int().positive().nullable().optional() })).mutation(async ({ input, ctx }) => { const existing = await getGeographyById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Geography record not found" }); const { id, ...changes } = input; const result = await updateGeography(id, { ...changes, parentId: changes.parentId ?? null }); await addAuditEvent({ actorId: ctx.user.id, action: "geography.updated", entityType: input.kind, entityId: id }); return result; }),
    removeGeography: managerOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const existing = await getGeographyById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Geography record not found" }); await removeGeography(input.id); await addAuditEvent({ actorId: ctx.user.id, action: "geography.removed", entityType: existing.kind, entityId: input.id }); return { success: true } as const; }),
    addClient: managerOnly.input(z.object({ name: z.string().min(2), city: z.string().optional(), province: z.string().optional(), address: z.string().optional(), contactPerson: z.string().optional(), phone: z.string().optional(), latitude: z.string().optional(), longitude: z.string().optional() })).mutation(async ({ input, ctx }) => { const result = await createClient({ ...input, createdBy: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "client.created", entityType: "client", entityId: result?.id }); return result; }),
    updateClient: managerOnly.input(z.object({ id: z.number().int().positive(), name: z.string().min(2), city: z.string().optional(), province: z.string().optional(), address: z.string().optional(), contactPerson: z.string().optional(), phone: z.string().optional(), latitude: z.string().optional(), longitude: z.string().optional() })).mutation(async ({ input, ctx }) => { const existing = await getClientById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Client not found" }); const { id, ...changes } = input; const result = await updateClient(id, changes); await addAuditEvent({ actorId: ctx.user.id, action: "client.updated", entityType: "client", entityId: id }); return result; }),
    removeClient: managerOnly.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input, ctx }) => { const existing = await getClientById(input.id); if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "Client not found" }); await removeClient(input.id); await addAuditEvent({ actorId: ctx.user.id, action: "client.removed", entityType: "client", entityId: input.id }); return { success: true } as const; }),
    tasks: protectedProcedure.query(({ ctx }) => ctx.user.role === "delegate" ? listTasksForDelegate(ctx.user.id) : ctx.user.role === "manager" ? listTasksForManager(ctx.user.id) : listAllTasks()),
    visit: protectedProcedure.input(z.object({ taskId: z.number().int().positive() })).query(({ input }) => getVisitByTaskId(input.taskId)),
    addTask: managerOnly.input(z.object({ delegateId: z.number().int().positive(), clientId: z.number().int().positive(), scheduledAt: z.date(), notes: z.string().optional() })).mutation(async ({ input, ctx }) => { const client = await getClientById(input.clientId); if (!client) throw new TRPCError({ code: "BAD_REQUEST", message: "Client not found" }); if (!canManagerAccessDelegate(ctx.user.role, ctx.user.id, input.delegateId, await listDelegateIdsForManager(ctx.user.id))) throw new TRPCError({ code: "FORBIDDEN", message: "This delegate is not assigned to your manager account" }); const result = await createTask({ ...input, createdBy: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "task.created", entityType: "task", entityId: result?.id }); return result; }),
    updateTaskStatus: protectedProcedure.input(z.object({ id: z.number().int().positive(), status: z.enum(["pending", "in_progress", "completed", "cancelled"]) })).mutation(async ({ input, ctx }) => { const task = await getTaskById(input.id); if (!task || !canUserUpdateTask(ctx.user.role, ctx.user.id, task.delegateId)) throw new TRPCError({ code: "FORBIDDEN", message: "You cannot update this task" }); const result = await updateTaskStatus(input.id, input.status); await addAuditEvent({ actorId: ctx.user.id, action: "task.status_changed", entityType: "task", entityId: input.id, metadata: JSON.stringify({ status: input.status }) }); return result; }),
    checkIn: protectedProcedure.input(z.object({ taskId: z.number().int().positive(), latitude: z.string(), longitude: z.string() })).mutation(async ({ input, ctx }) => { const task = await getTaskById(input.taskId); if (!task || !canUserUpdateTask(ctx.user.role, ctx.user.id, task.delegateId)) throw new TRPCError({ code: "FORBIDDEN", message: "You cannot check in to this task" }); const result = await upsertVisit({ taskId: input.taskId, checkInAt: new Date(), checkInLat: input.latitude, checkInLng: input.longitude }); await updateTaskStatus(input.taskId, "in_progress"); await addAuditEvent({ actorId: ctx.user.id, action: "visit.checked_in", entityType: "task", entityId: input.taskId }); return result; }),
    saveVisitReport: protectedProcedure.input(z.object({ taskId: z.number().int().positive(), report: z.string().trim().min(1).max(10000) })).mutation(async ({ input, ctx }) => { const task = await getTaskById(input.taskId); if (!task || !canUserUpdateTask(ctx.user.role, ctx.user.id, task.delegateId)) throw new TRPCError({ code: "FORBIDDEN", message: "You cannot update this visit" }); const result = await upsertVisit({ taskId: input.taskId, ...prepareVisitReport(input.report) }); await addAuditEvent({ actorId: ctx.user.id, action: "visit.report_saved", entityType: "task", entityId: input.taskId }); return result; }),
    checkOut: protectedProcedure.input(z.object({ taskId: z.number().int().positive(), latitude: z.string(), longitude: z.string(), report: z.string().optional() })).mutation(async ({ input, ctx }) => { const task = await getTaskById(input.taskId); if (!task || !canUserUpdateTask(ctx.user.role, ctx.user.id, task.delegateId)) throw new TRPCError({ code: "FORBIDDEN", message: "You cannot check out of this task" }); const result = await upsertVisit({ taskId: input.taskId, checkOutAt: new Date(), checkOutLat: input.latitude, checkOutLng: input.longitude, report: input.report }); await updateTaskStatus(input.taskId, "completed"); await addAuditEvent({ actorId: ctx.user.id, action: "visit.checked_out", entityType: "task", entityId: input.taskId }); return result; }),
    uploadEvidence: protectedProcedure.input(z.object({ visitId: z.number().int().positive(), kind: z.enum(["photo", "audio", "signature", "document"]), fileName: z.string().min(1).max(180), mimeType: z.string().max(120), base64: z.string().min(20).max(15_000_000) })).mutation(async ({ input, ctx }) => { const buffer = Buffer.from(input.base64.replace(/^data:[^;]+;base64,/, ""), "base64"); const uploaded = await storagePut(`evidence/${ctx.user.id}/${input.fileName}`, buffer, input.mimeType); const evidenceId = await addEvidence({ visitId: input.visitId, kind: input.kind, storageKey: uploaded.key, mimeType: input.mimeType, sizeBytes: buffer.byteLength, uploadedBy: ctx.user.id }); await addAuditEvent({ actorId: ctx.user.id, action: "evidence.uploaded", entityType: "visit", entityId: input.visitId, metadata: JSON.stringify({ kind: input.kind, evidenceId }) }); return { evidenceId, url: uploaded.url } as const; }),
  }),
});

export type AppRouter = typeof appRouter;
