import React, { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "en" | "ar";

const LANGUAGE_STORAGE_KEY = "ffm-language";

const messages = {
  en: {
    language: "Language",
    english: "English",
    arabic: "العربية",
    signIn: "Sign in securely",
    signOut: "Sign out",
    loadingManager: "Loading FFM Manager…",
    fieldForceManagement: "Field Force Management",
    manager: "Manager",
    administrator: "Administrator",
    superManager: "Super Manager",
    delegate: "Delegate",
    warehouseHero: "Warehouse Hero",
    dashboard: "Dashboard",
    myProfile: "My Profile",
    delegates: "Delegates",
    warehouseHeroes: "Warehouse Heroes",
    heroLeadActivity: "Hero Lead Activity",
    clients: "Clients",
    tasks: "Tasks",
    surgeries: "Surgeries",
    surgeryCalendar: "Surgery Calendar",
    preOpReadiness: "Pre-op Readiness",
    visitPlans: "Visit Plans",
    workLog: "Weekly Visits & Daily Reports",
    travelExpenses: "Travel Expenses",
    messages: "Messages",
    reports: "Reports",
    geography: "Geography",
    administration: "Administration",
    diagnostics: "Diagnostics",
    operations: "Operations",
    stockManagement: "Stock Management",
    liveSystem: "Live system",
    welcomeToFfm: "Welcome to FFM",
    onboardingTitle: "Start with your operational overview",
    onboardingText: "Use Administration to invite users, Tasks to assign work, and Reports to export filtered summaries.",
    gotIt: "Got it",
    operationalOverview: "Operational overview",
    goodDay: "Good day, {name}.",
    operationalSubtitle: "A precise view of today’s field activity across the FFM network.",
    viewStock: "View stock",
    createTask: "Create task",
    thisWeek: "This week",
    weeklySnapshot: "Weekly operations snapshot",
    saturdayToThursday: "Saturday {start} to Thursday {end}",
    hideEmptyCards: "Hide empty cards",
    showEmptyCards: "Show empty cards",
    plannedTasks: "Planned tasks",
    completed: "Completed",
    open: "Open",
    workLogAlerts: "Work Log alerts",
    activeDelegates: "Active Delegates",
    visitsToday: "Visits Today",
    pendingTasks: "Pending Tasks",
    coverage: "Coverage",
    syncingDatabase: "Syncing database",
    assignedLiveDelegates: "Assigned live delegates",
    liveTaskRecords: "Live task records",
    livePendingTasks: "Live pending tasks",
    liveClientRecords: "Live client records",
    profileIdentity: "Personal identity",
    profileDescription: "Set the name colleagues will see in messages, surgeries, tasks, readiness, and logistics workspaces.",
    displayName: "Display name",
    enterFullName: "Enter your full name",
    registeredEmail: "Your registered email, {email}, is used only when no display name has been saved.",
    department: "Department",
    notAssigned: "Not assigned",
    departmentAdministration: "Department structures and assignments are maintained by the Administrator.",
    saveProfile: "Save profile",
    saving: "Saving…",
    authenticationRequired: "Authentication is required for all app access.",
    loginDescription: "Secure control panel for delegates, visits, clients, and clinical operations.",
    fieldRepresentative: "Field Representative",
    delegateLoginDescription: "Securely manage tasks, visits, clinical contacts, and field evidence.",
    myTasks: "My Tasks",
    visit: "Visit",
    profile: "Profile",
    liveLocationOn: "Live location on",
    liveLocationOff: "Live location off",
    completeVisit: "Complete each visit with confidence",
    delegateOnboardingText: "Open a task, check in with GPS, capture the report and evidence, then check out.",
    todayRoute: "Today’s route",
    syncingAssignedVisits: "Syncing assigned visits…",
    assignedVisits: "{count} assigned visits · live records",
    live: "Live",
    assignedTasks: "Assigned tasks",
    loadingAssignedTasks: "Loading assigned tasks…",
    unableLoadAssignedTasks: "Unable to load assigned tasks: {message}",
    noAssignedTasks: "No assigned tasks yet. Your manager will publish new visits here.",
    scheduledFieldVisit: "Scheduled field visit",
    currentAssignment: "Current assignment",
    noAssignmentSelected: "No assignment selected",
    schedulePending: "Schedule pending",
    locationPending: "Location pending",
    completedAt: "Completed {date}",
    checkedInAt: "Checked in {date}",
    notCheckedIn: "Not checked in",
    liveClientCoordinates: "Live client coordinates",
    clientCoordinatesUnavailable: "Client coordinates unavailable",
    taskStatus: "Task status",
    pending: "Pending",
    inProgress: "In progress",
    cancelled: "Cancelled",
    checkIn: "Check in",
    checkingIn: "Checking in…",
    checkOut: "Check out",
    checkingOut: "Checking out…",
    visitReport: "Visit report",
    visitReportPlaceholder: "Capture purpose, discussion points, and follow-up actions…",
    saveReport: "Save report",
    savingReport: "Saving report…",
    visitReportSaved: "Visit report saved to the live record.",
    visitEvidence: "Visit evidence",
    photo: "Photo",
    audio: "Audio",
    signature: "Signature",
    saveSignature: "Save signature",
    uploadingEvidence: "Uploading evidence…",
    evidenceUploaded: "Evidence uploaded securely.",
    financeWorkflow: "Finance workflow",
    claimReleaseWorkflow: "Claim & release workflow",
    backToWorkspace: "Back to workspace",
    secureApprovalTrail: "Secure approval trail",
    travelExpenseSheet: "Travel expense sheet",
    travelExpenseIntro: "Submit a clear claim. Track the approval. Record the release.",
    travelExpenseDescription: "Every FFM member can submit their own travel expenses. A claim stays pending until the claimant’s Manager and the designated Operational Manager approve it. The release date is recorded automatically when the released amount is confirmed.",
    travelLoginDescription: "Sign in to submit and track your FFM travel claims.",
    warehouseHeroApp: "Warehouse Hero app",
    hospitalLogistics: "Hospital logistics",
    logisticsLoginDescription: "Secure hospital delivery tracking for warehouse personnel.",
    warehouseHeroAccessRequired: "Warehouse Hero access required",
    warehouseHeroAccessDescription: "This workspace is available only to accounts invited as Warehouse Heroes.",
    delivery: "Delivery",
    deliveryShift: "Delivery shift",
    gpsTrackingOn: "GPS tracking on",
    gpsTrackingOff: "GPS tracking off",
    teamMessages: "Team messages",
    recipient: "Recipient",
    chooseFfmMember: "Choose an FFM member",
    message: "Message",
    deliveryMessagePlaceholder: "Write a delivery or operational update…",
    sendMessage: "Send message",
    sending: "Sending…",
    shareDeliveryLocation: "Share delivery location",
    liveCameraDeliveryProof: "Live-camera delivery proof",
    deliveryProofHistory: "Your delivery-proof history",
    fieldPerformance: "Field performance",
    workLogRestricted: "Work Log is role restricted",
    workLogRestrictedDescription: "This workspace is for Delegates, Managers, and Administrators.",
    delegateWorkLogTitle: "My hospital plans & doctor visits",
    managerWorkLogTitle: "My plans, reports & Delegate review",
    workLogDescription: "The Delegate workweek runs Saturday through Thursday; Friday is the only weekend day. Every plan day contains 3–6 hospitals, each with multiple registered doctors if needed.",
    addHospital: "Add hospital",
    addLinkedDoctor: "Add linked doctor",
    sixDayWorkweekPlan: "Six-day workweek plan",
    dailyVisitsReport: "Daily visits & report",
    weekStartingSaturday: "Week starting Saturday",
    submitWorkweekPlan: "Submit Saturday–Thursday plan",
    reportDate: "Report date",
    submitDailyReport: "Submit daily report",
    weeklyPlans: "Weekly plans",
    dailyReports: "Daily reports",
    sharedSurgeryCalendar: "Shared surgery calendar",
    surgeryCalendarLoginDescription: "Sign in to view the current surgery schedule.",
    surgeryPlanning: "Surgery planning",
    sharedPlanning: "Shared planning",
    delegateWorkspace: "Delegate workspace",
    allRolesCanView: "All roles can view",
    dayOfSurgeryControl: "Day-of-surgery control",
    surgeryCalendarIntro: "Plan early. Resolve only on the surgery day.",
    surgeryCalendarDescription: "Choose from the supplied product catalogue or enter a missing implant directly. Pricing is recorded only on the surgery record.",
    liveSurgeries: "{count} live surgeries",
    preoperativeControl: "Preoperative control",
    surgeryReadiness: "Surgery readiness",
    readinessLoginDescription: "Sign in to view preparation status.",
    liveReadiness: "Live readiness",
    preparationWindow: "2–7 day preparation window",
    readinessIntro: "Confirm readiness before the surgery day.",
    readinessDescription: "Use this five-step checklist to confirm hospital readiness, approved implant availability, the assigned Delegate, Warehouse preparation, and Hospital delivery before the procedure.",
    upcomingSurgeryRecords: "Upcoming surgery records",
  },
  ar: {
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    signIn: "تسجيل الدخول بأمان",
    signOut: "تسجيل الخروج",
    loadingManager: "جارٍ تحميل مدير FFM…",
    fieldForceManagement: "إدارة القوى الميدانية",
    manager: "مدير",
    administrator: "مسؤول النظام",
    superManager: "مدير عام",
    delegate: "مندوب",
    warehouseHero: "بطل المستودع",
    dashboard: "لوحة التحكم",
    myProfile: "ملفي الشخصي",
    delegates: "المندوبون",
    warehouseHeroes: "أبطال المستودع",
    heroLeadActivity: "نشاط قائد الأبطال",
    clients: "العملاء",
    tasks: "المهام",
    surgeries: "العمليات الجراحية",
    surgeryCalendar: "تقويم العمليات",
    preOpReadiness: "الاستعداد قبل العملية",
    visitPlans: "خطط الزيارات",
    workLog: "الزيارات الأسبوعية والتقارير اليومية",
    travelExpenses: "مصروفات السفر",
    messages: "الرسائل",
    reports: "التقارير",
    geography: "المناطق الجغرافية",
    administration: "الإدارة",
    diagnostics: "التشخيص",
    operations: "العمليات",
    stockManagement: "إدارة المخزون",
    liveSystem: "النظام متصل",
    welcomeToFfm: "مرحبًا بك في FFM",
    onboardingTitle: "ابدأ بنظرتك العامة للعمليات",
    onboardingText: "استخدم الإدارة لدعوة المستخدمين، والمهام لتوزيع العمل، والتقارير لتصدير الملخصات المفلترة.",
    gotIt: "فهمت",
    operationalOverview: "نظرة عامة على العمليات",
    goodDay: "مرحبًا، {name}.",
    operationalSubtitle: "عرض دقيق لنشاط العمل الميداني اليومي عبر شبكة FFM.",
    viewStock: "عرض المخزون",
    createTask: "إنشاء مهمة",
    thisWeek: "هذا الأسبوع",
    weeklySnapshot: "ملخص العمليات الأسبوعي",
    saturdayToThursday: "من السبت {start} إلى الخميس {end}",
    hideEmptyCards: "إخفاء البطاقات الفارغة",
    showEmptyCards: "إظهار البطاقات الفارغة",
    plannedTasks: "المهام المخططة",
    completed: "مكتملة",
    open: "مفتوحة",
    workLogAlerts: "تنبيهات سجل العمل",
    activeDelegates: "المندوبون النشطون",
    visitsToday: "زيارات اليوم",
    pendingTasks: "المهام المعلقة",
    coverage: "التغطية",
    syncingDatabase: "جارٍ مزامنة قاعدة البيانات",
    assignedLiveDelegates: "المندوبون المعيّنون",
    liveTaskRecords: "سجلات المهام الحالية",
    livePendingTasks: "المهام المعلقة الحالية",
    liveClientRecords: "سجلات العملاء الحالية",
    profileIdentity: "الهوية الشخصية",
    profileDescription: "حدد الاسم الذي سيراه الزملاء في الرسائل والعمليات والمهام والاستعداد ومساحات عمل الخدمات اللوجستية.",
    displayName: "الاسم الظاهر",
    enterFullName: "أدخل اسمك الكامل",
    registeredEmail: "يستخدم بريدك المسجل، {email}، فقط عند عدم حفظ اسم ظاهر.",
    department: "القسم",
    notAssigned: "غير معيّن",
    departmentAdministration: "تتم إدارة هيكل الأقسام والتعيينات بواسطة مسؤول النظام.",
    saveProfile: "حفظ الملف الشخصي",
    saving: "جارٍ الحفظ…",
    authenticationRequired: "المصادقة مطلوبة للوصول إلى التطبيق.",
    loginDescription: "لوحة تحكم آمنة للمندوبين والزيارات والعملاء والعمليات السريرية.",
    fieldRepresentative: "ممثل ميداني",
    delegateLoginDescription: "أدر المهام والزيارات وجهات الاتصال السريرية وأدلة العمل الميداني بأمان.",
    myTasks: "مهامي",
    visit: "الزيارة",
    profile: "الملف الشخصي",
    liveLocationOn: "الموقع المباشر مفعّل",
    liveLocationOff: "الموقع المباشر غير مفعّل",
    completeVisit: "أكمل كل زيارة بثقة",
    delegateOnboardingText: "افتح المهمة، وسجّل الحضور عبر GPS، وأدخل التقرير والأدلة، ثم سجّل المغادرة.",
    todayRoute: "مسار اليوم",
    syncingAssignedVisits: "جارٍ مزامنة الزيارات المعيّنة…",
    assignedVisits: "{count} زيارة معيّنة · سجلات مباشرة",
    live: "مباشر",
    assignedTasks: "المهام المعيّنة",
    loadingAssignedTasks: "جارٍ تحميل المهام المعيّنة…",
    unableLoadAssignedTasks: "تعذر تحميل المهام المعيّنة: {message}",
    noAssignedTasks: "لا توجد مهام معيّنة بعد. سيضيف مديرك الزيارات الجديدة هنا.",
    scheduledFieldVisit: "زيارة ميدانية مجدولة",
    currentAssignment: "المهمة الحالية",
    noAssignmentSelected: "لم يتم اختيار مهمة",
    schedulePending: "الجدول قيد الانتظار",
    locationPending: "الموقع قيد الانتظار",
    completedAt: "اكتملت في {date}",
    checkedInAt: "تم تسجيل الحضور في {date}",
    notCheckedIn: "لم يتم تسجيل الحضور",
    liveClientCoordinates: "إحداثيات العميل المباشرة",
    clientCoordinatesUnavailable: "إحداثيات العميل غير متاحة",
    taskStatus: "حالة المهمة",
    pending: "معلقة",
    inProgress: "قيد التنفيذ",
    cancelled: "ملغاة",
    checkIn: "تسجيل الحضور",
    checkingIn: "جارٍ تسجيل الحضور…",
    checkOut: "تسجيل المغادرة",
    checkingOut: "جارٍ تسجيل المغادرة…",
    visitReport: "تقرير الزيارة",
    visitReportPlaceholder: "سجّل هدف الزيارة ونقاط النقاش وإجراءات المتابعة…",
    saveReport: "حفظ التقرير",
    savingReport: "جارٍ حفظ التقرير…",
    visitReportSaved: "تم حفظ تقرير الزيارة في السجل المباشر.",
    visitEvidence: "أدلة الزيارة",
    photo: "صورة",
    audio: "تسجيل صوتي",
    signature: "التوقيع",
    saveSignature: "حفظ التوقيع",
    uploadingEvidence: "جارٍ رفع الأدلة…",
    evidenceUploaded: "تم رفع الأدلة بأمان.",
    financeWorkflow: "سير عمل الشؤون المالية",
    claimReleaseWorkflow: "سير عمل المطالبة والصرف",
    backToWorkspace: "العودة إلى مساحة العمل",
    secureApprovalTrail: "سجل موافقات آمن",
    travelExpenseSheet: "نموذج مصروفات السفر",
    travelExpenseIntro: "قدّم مطالبة واضحة. تابع الموافقة. وسجّل الصرف.",
    travelExpenseDescription: "يمكن لكل عضو في FFM تقديم مصروفات سفره. تبقى المطالبة معلقة حتى يوافق عليها مدير المطالب والمدير التشغيلي المعيّن. يُسجل تاريخ الصرف تلقائيًا عند تأكيد المبلغ المصروف.",
    travelLoginDescription: "سجّل الدخول لتقديم مطالبات سفر FFM ومتابعتها.",
    warehouseHeroApp: "تطبيق بطل المستودع",
    hospitalLogistics: "لوجستيات المستشفى",
    logisticsLoginDescription: "تتبع آمن لتسليمات المستشفيات لموظفي المستودع.",
    warehouseHeroAccessRequired: "مطلوب وصول بطل المستودع",
    warehouseHeroAccessDescription: "تتوفر مساحة العمل هذه للحسابات المدعوة كأبطال للمستودع فقط.",
    delivery: "التسليم",
    deliveryShift: "وردية التسليم",
    gpsTrackingOn: "تتبع GPS مفعّل",
    gpsTrackingOff: "تتبع GPS غير مفعّل",
    teamMessages: "رسائل الفريق",
    recipient: "المستلم",
    chooseFfmMember: "اختر عضوًا من FFM",
    message: "الرسالة",
    deliveryMessagePlaceholder: "اكتب تحديثًا للتسليم أو العمليات…",
    sendMessage: "إرسال الرسالة",
    sending: "جارٍ الإرسال…",
    shareDeliveryLocation: "مشاركة موقع التسليم",
    liveCameraDeliveryProof: "إثبات تسليم بالكاميرا المباشرة",
    deliveryProofHistory: "سجل إثباتات التسليم الخاصة بك",
    fieldPerformance: "الأداء الميداني",
    workLogRestricted: "سجل العمل مقيّد حسب الدور",
    workLogRestrictedDescription: "مساحة العمل هذه للمندوبين والمديرين ومسؤولي النظام.",
    delegateWorkLogTitle: "خطط مستشفياتي وزيارات الأطباء",
    managerWorkLogTitle: "خططي وتقاريري ومراجعة المندوبين",
    workLogDescription: "يمتد أسبوع عمل المندوب من السبت إلى الخميس، والجمعة هي يوم العطلة الوحيد. يحتوي كل يوم في الخطة على 3 إلى 6 مستشفيات، مع عدة أطباء مسجلين عند الحاجة.",
    addHospital: "إضافة مستشفى",
    addLinkedDoctor: "إضافة طبيب مرتبط",
    sixDayWorkweekPlan: "خطة أسبوع العمل لستة أيام",
    dailyVisitsReport: "الزيارات والتقرير اليومي",
    weekStartingSaturday: "الأسبوع الذي يبدأ يوم السبت",
    submitWorkweekPlan: "إرسال خطة السبت إلى الخميس",
    reportDate: "تاريخ التقرير",
    submitDailyReport: "إرسال التقرير اليومي",
    weeklyPlans: "الخطط الأسبوعية",
    dailyReports: "التقارير اليومية",
    sharedSurgeryCalendar: "تقويم العمليات المشترك",
    surgeryCalendarLoginDescription: "سجّل الدخول لعرض جدول العمليات الحالي.",
    surgeryPlanning: "تخطيط العمليات",
    sharedPlanning: "التخطيط المشترك",
    delegateWorkspace: "مساحة عمل المندوب",
    allRolesCanView: "يمكن لجميع الأدوار العرض",
    dayOfSurgeryControl: "التحكم في يوم العملية",
    surgeryCalendarIntro: "خطط مبكرًا. واتخذ القرار فقط في يوم العملية.",
    surgeryCalendarDescription: "اختر من كتالوج المنتجات المورّد أو أدخل غرسة غير موجودة مباشرة. يُسجل السعر في سجل العملية فقط.",
    liveSurgeries: "{count} عملية مباشرة",
    preoperativeControl: "التحكم قبل العملية",
    surgeryReadiness: "الاستعداد للعملية",
    readinessLoginDescription: "سجّل الدخول لعرض حالة الاستعداد.",
    liveReadiness: "الاستعداد المباشر",
    preparationWindow: "نافذة التحضير من يومين إلى سبعة أيام",
    readinessIntro: "أكد الجاهزية قبل يوم العملية.",
    readinessDescription: "استخدم قائمة التحقق المكونة من خمس خطوات لتأكيد جاهزية المستشفى، وتوفر الغرسات المعتمدة، والمندوب المعيّن، وتحضير المستودع، والتسليم إلى المستشفى قبل الإجراء.",
    upcomingSurgeryRecords: "سجلات العمليات القادمة",
  },
} as const;

export type TranslationKey = keyof typeof messages.en;

type LanguageContextValue = {
  language: AppLanguage;
  isRtl: boolean;
  setLanguage: (language: AppLanguage) => void;
  t: (key: TranslationKey, values?: Record<string, string | number>) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<AppLanguage>(() => {
    if (typeof window === "undefined") return "en";
    return localStorage.getItem(LANGUAGE_STORAGE_KEY) === "ar" ? "ar" : "en";
  });

  useEffect(() => {
    const root = document.documentElement;
    root.lang = language;
    root.dir = language === "ar" ? "rtl" : "ltr";
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    isRtl: language === "ar",
    setLanguage,
    t: (key, values) => Object.entries(values ?? {}).reduce<string>(
      (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
      messages[language][key],
    ),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
