import { useState } from "react";
import { CalendarClock, Link2Off, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

const toDateInput = (value: Date | string) => new Date(value).toISOString().slice(0, 10);
const maximumDate = () => new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

export function ReportShareManagement() {
  const [notice, setNotice] = useState("");
  const [expiryById, setExpiryById] = useState<Record<number, string>>({});
  const sharesQuery = trpc.admin.monthlyDepartmentReportShares.useQuery();
  const revokeShare = trpc.admin.revokeMonthlyDepartmentReportShare.useMutation({ onSuccess: () => { setNotice("Report link revoked immediately."); sharesQuery.refetch(); }, onError: error => setNotice(error.message) });
  const updateExpiry = trpc.admin.updateMonthlyDepartmentReportShareExpiry.useMutation({ onSuccess: (share) => { setNotice(`Report link expiry updated to ${new Date(share.expiresAt).toLocaleString()}.`); sharesQuery.refetch(); }, onError: error => setNotice(error.message) });
  const selectedExpiry = (id: number, expiresAt: Date | string) => expiryById[id] ?? toDateInput(expiresAt);
  return <Card className="blueprint-card mb-6"><CardHeader><div><CardTitle>Shared monthly report links</CardTitle><p className="muted">Administrators can set or extend an active secure link up to 90 days ahead, or revoke access immediately. Tokens and report contents are never displayed here.</p></div></CardHeader><CardContent>{notice && <div className={(revokeShare.error || updateExpiry.error) ? "admin-feedback error mb-3" : "admin-feedback success mb-3"}>{notice}</div>}{sharesQuery.isLoading ? <div className="admin-feedback">Loading report links…</div> : sharesQuery.error ? <div className="admin-feedback error">{sharesQuery.error.message}</div> : sharesQuery.data?.length ? <div className="space-y-3">{sharesQuery.data.map(share => <div key={share.id} className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-cyan-400/20 bg-slate-950/20 p-3"><div><div className="flex items-center gap-2"><strong>{share.month}</strong><Badge variant="outline" className={share.active ? "border-emerald-400/40 text-emerald-300" : "border-slate-500 text-slate-400"}>{share.active ? "Active" : "Expired"}</Badge></div><p className="muted mt-1 text-xs">Created by {share.createdByName} · expires {new Date(share.expiresAt).toLocaleString()}</p></div>{share.active ? <div className="flex flex-wrap items-center gap-2"><label className="sr-only" htmlFor={`report-share-expiry-${share.id}`}>Expiry date for report link {share.month}</label><input id={`report-share-expiry-${share.id}`} className="h-9 rounded-md border border-cyan-400/30 bg-slate-950 px-2 text-sm text-slate-100" type="date" min={new Date(Date.now() + 86_400_000).toISOString().slice(0, 10)} max={maximumDate()} value={selectedExpiry(share.id, share.expiresAt)} disabled={updateExpiry.isPending || revokeShare.isPending} onChange={(event) => setExpiryById(current => ({ ...current, [share.id]: event.target.value }))}/><Button variant="outline" size="sm" disabled={updateExpiry.isPending || revokeShare.isPending || !selectedExpiry(share.id, share.expiresAt)} onClick={() => updateExpiry.mutate({ id: share.id, expiresOn: selectedExpiry(share.id, share.expiresAt) })}><CalendarClock size={15}/>{updateExpiry.isPending ? "Saving…" : "Set expiry"}</Button><Button variant="outline" size="sm" disabled={revokeShare.isPending || updateExpiry.isPending} onClick={() => revokeShare.mutate({ id: share.id })}><Link2Off size={15}/>{revokeShare.isPending ? "Revoking…" : "Revoke access"}</Button></div> : <span className="muted text-xs inline-flex items-center gap-1"><ShieldCheck size={14}/>Inactive</span>}</div>)}</div> : <div className="admin-feedback">No shared monthly report links have been created.</div>}</CardContent></Card>;
}
